name: tasked
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  floating_bottom_navigation_bar: ^1.5.2
  smooth_page_indicator: ^1.0.0+2
  date_picker_timeline: ^1.2.3
  get: ^4.6.3
  date_time_picker: ^2.1.0
  circular_countdown_timer: ^0.2.1
  sqflite: ^2.0.2+1
  intl: ^0.17.0
  flutter_staggered_animations: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/launcher_Icons/io_launcher_icon.png"
  image_path_android: "assets/launcher_Icons/android_launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/svg/
    - assets/launcher_Icons/
