name: recipe_getx
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  get: ^4.6.5
  custom_input_text: ^0.1.3
  animated_login: ^1.5.4
  fancy_password_field: ^1.0.4
  avatars: ^3.0.2
  outline_search_bar: ^2.3.0
  animated_bottom_navigation_bar: ^1.0.1
  contained_tab_bar_view: ^0.8.0
  tab_container: ^2.0.0
  dotted_border: ^2.0.0+2
  flutter_input_field: ^0.0.5
  device_preview: ^1.1.0
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.1+1
  html: ^0.15.0
  beautiful_soup_dart: ^0.3.0
  url_launcher: ^6.1.5
  webview_flutter: ^3.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/loading/
    - assets/images/
    - assets/profile/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
