name: parcel_delivery_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.6.1
  google_fonts: ^2.3.2
  svg_icon: ^0.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/Avatar/Small.png
    - assets/Icon/Tab bar/Navbar/Item/Inactive.svg
    - assets/Icon/Tab bar/My parcels.svg
    - assets/Icon/Tab bar/Nav/Tab bar/Item/Inactive.svg
    - assets/Icon/Tab bar/Send parcels.svg
    - assets/Icon/Tab bar/Navbar/Item/Inactive Copy.svg
    - assets/images/
    - assets/Icon/Tab bar/Parcel Center.svg
    - assets/Icon/QR Code.svg
    - assets/Media/Image/Logo/Amazon.svg
    - assets/Element/Link/Active.svg
    - assets/illustration/small box.png
    - assets/illustration/Envelope.png
    - assets/illustration/Ski/Asset/illustration/Custom parcel.png
    - assets/illustration/Ski/Asset/illustration/Big box.png
